spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/update_system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Отключаем JAXB модуль Jackson (чтобы избежать ClassNotFoundException)
        type.json_format_mapper: org.hibernate.type.format.jackson.JacksonJsonFormatMapper
  h2:
    console:
      enabled: false

telegram:
  bot:
    token: "321321312321321321"
    chat-id: "321312321321"